#+TITLE: Programmation synchrone 2020/2021 -- M2 Informatique & EIDD
#+AUTHOR: Adrien Guatto
#+EMAIL: guatto@irif.org
#+LANGUAGE: fr
#+OPTIONS: ^:nil p:nil

Ce fichier contient le journal du cours. Il fait référence aux
[notes](notes-de-cours-progsync.pdf).

* Cours 01 <2020-09-29>
  Cette séance a traité des notes de cours, de Introduction à Premiers
  programmes inclus. On a même été un peu au delà, avec un premier exemple bref
  de noeud Heptagon séquentiel (à état non-trivial).
* Cours 02 <2020-10-06>
  Cette séance a traité des notes de cours, deuxième section, jusqu'à
  "Causalité" inclus.
* Cours 03 <2020-10-13>
  Cette séance a couvert la deuxième section des notes de cours, jusqu'au début
  de la section "automates". En revanche, les règles du calcul d'horloge et
  l'exemple de l'intégrateur n'ont pas été traités.
* Cours 04 <2020-10-20>
  On a commencé par revenir sur les horloges discutées lors du cours 3, en
  discutant des règles qui dictent si une expression est correcte du point de
  vue des horloges, puis en présentant un exemple (un intégrateur désactivable).
  On a ensuite détaillé le fonctionnement des automates (types de transition,
  mémoires ~last~) comme dans les notes de cours.
